server:
  port: 1057
spring:
  servlet:
    multipart:
      #设置单个文件大小
      max-file-size: 100MB
      #设置单次请求文件的总大小
      max-request-size: 100MB

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    # 自定义秘钥
    password: ${password}
    string-output-type: base64
    property:
      prefix: ENC(
      suffix: )
